apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-cwxgoweb
  namespace: cwx
  labels:
    app: dev-cwxgoweb

spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-cwxgoweb
  template:
    metadata:
      labels:
        app: dev-cwxgoweb
    spec:
      restartPolicy: Always
      containers:
      - name: dev-cwxgoweb
        image: registry.services.wait/cwx/cwxgoweb:latest
        ports:
          - containerPort: 19002
        env:
        - name: CWX_WEBSERVER_ENABLE
          value: "true"
        - name: CWX_WEBSERVER_PORT
          value: "19002"

        - name: CWX_DB_ADDR
          value: "wcn7.server.wait"
        - name: CWX_DB_PORT
          value: "3306"
        - name: CWX_DB_USER
          value: "wait"
        - name: CWX_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wait-secret
              key: wait-pw
        - name: CWX_DB_CHARSET
          value: "utf8mb4"
        - name: CWX_GENERATEDATA_DB_NAME
          value: "doc"

        - name: CWX_METRICS_PORT
          value: "19003"
