
name: cwxgoweb

on:
  push:
    branches: [ main ]

env:
  APP_NAME: myapp

jobs:
  build-and-deploy:
    # 需要设定为 私有运行器
    runs-on: self-hosted

    steps:
      - name: Checkout 检出代码
        uses: actions/checkout@v4

      - name: Set up Go env
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: 构建 BuiLd
        run: |
          cd cmd && go build -o app

