
name: auto build

on:
  push:
    branches: [ main ]

env:
  APP_NAME: myapp

jobs:
  build-and-deploy:
    name: 编译go程序

    runs-on: self-hosted

    steps:
      - name: Checkout 检出代码
        uses: actions/checkout@main

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        run: cd cmd && go build -o app
