
name: cwxgoweb

on:
  push:
    branches: [ main ]

env:
  APP_NAME: myapp

jobs:
  build-and-deploy:
    name: 编译go程序
    # 需要设定为 私有运行器
    runs-on: self-hosted

    steps:
      - name: Checkout 检出代码
        uses: actions/checkout@main

      # - name: Set up Go env
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: '1.21'

      - name: 编译程序
        run: |
          export PATH=/opt/go/bin:$PATH
          export GOPROXY='https://goproxy.cn,direct'
          /opt/go/bin/go version
          go version
          cd cmd && go build -o app
